### ISSUE TITLE
require() + return obsolete

### ISSUE THREAD

**Issue by Rendez** [Atanamo/PHP-Codeshift#3]
First, thanks a lot for putting this lib together. There are a few things missing, like better docs and I'd like to contribute to that. But first, I wanted to point out that PHP 7 is throwing on codemods with a "return" at the end. Looking at the codemod loader I can see why is necessary:

```php
public function loadCodemodToTransformer($codemodFilePath) {
        $codemodClass = null;
        $loadedFromCache = false;

        // Load codemod class
        if (!isset($this->codemodClasses[$codemodFilePath])) {
            if (file_exists($codemodFilePath)) {
                $codemodClass = require $codemodFilePath;
                                              // ^^^
```
Could we move this to the autoloader? For that I guess that codemods should be defined within a user's namespace or the Codemod namespace itself.

**Comment by Atanamo** [comment]
Oh, there may be issues here, you are right.
I forgot to enable PHP notices.

There is a notice "Use of undefined constant <Class name>...", if the codemod class is returned like described in the examples:
```php
  class Example { } 
  return Example;
```

Moreover, if you are using a namespace for your codemod, it may result in fatal error "Uncaught Error: Undefined constant 'YourNamespace\YourCodemodClass'..."

The correct method is to return a string with the class name. This should work in any case and without any notices or errors.
```php
  return '\SomeNamespace\Example';
```

Maybe this solves your problems?
I will fix the examples and the docs then.

Otherwise we have to take a very different look on it, I agree. 
But it would be strange - the return mechanism is a documented feature of PHP's require/include mechanism: http://php.net/manual/en/function.include.php

(I pointing to the include docs here, because the require doc itself points to it.)
--> See section "Handling Returns:", right before example #4. Examples #4 and #5 also demonstrate it.

--

The reason for the current method of loading the codemod is its simplicity.
The loader needs the class name to initialize the class, but only knows the file name. And I wanted to allow any class name without any naming conventions or other constraints...

So the file has to somehow export the class name. This allows the loader to use the following feature: http://php.net/manual/en/language.namespaces.dynamic.php.

**Comment by Rendez** [comment]
Thanks for looking into this, makes total sense to use the stringified namespace so the solutions sounds good to me. If you want to create a branch and later a (pre)release I'd be happy to try it out locally asap.

**Comment by Atanamo** [comment]
I've updated the examples and docs now - in the master branch. I don't think a new release is necessary for this?

Please let me now, if there are any further problems. :-)

**Comment by Rendez** [comment]
Amazing, thanks! 
> I don't think a new release is necessary for this?

Only if you want the README to display the changes for people landing here or opening it from their vendor folders ;)
