### ISSUE TITLE
Remove if statement if true

### ISSUE THREAD

**Issue by oligriffiths** [Atanamo/PHP-Codeshift#4]
Hi

I'd like to replace:
```
if (true) {
    $a = 1;
}
```
with
```
$a = 1;
```

AFAICT one needs to return a `Node` from the node visitor functions, so I'm not sure how to do this as `stmts` is an array.

Can anyone help?

Thanks

**Comment by Atanamo** [comment]
Hi,

I stumpled around the docs of PHP-Parser a while and started to think about complex solutions as I found a quiet simple answer:

Just use `leaveNode` instead of `enterNode`.  :-)
The docs for `leaveNode` specify that you can return an array of nodes, which is "merged into the parent array (at the position of the $node)".
(See https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/NodeVisitor.php)

That's one of the differencies between the enter and leave methods - besides the possibility of deleting a node, and so on.

But I didn't try it. Please let me know if it's working or not.
